export const KEY_LIST_REQUEST = 'KEY_LIST_REQUEST';
export const KEY_LIST_SUCCESS = 'KEY_LIST_SUCCESS';
export const KEY_LIST_FAIL = 'KEY_LIST_FAIL';
export const KEY_LIST_CLEAR = 'KEY_LIST_CLEAR';

export const KEY_CREATE_REQUEST = 'KEY_CREATE_REQUEST';
export const KEY_CREATE_SUCCESS = 'KEY_CREATE_SUCCESS';
export const KEY_CREATE_FAIL = 'KEY_CREATE_FAIL';
