export const SPREADSHEET_LIST_REQUEST = 'SPREADSHEET_LIST_REQUEST';
export const SPREADSHEET_LIST_SUCCESS = 'SPREADSHEET_LIST_SUCCESS';
export const SPREADSHEET_LIST_FAIL = 'SPREADSHEET_LIST_FAIL';

export const SPREADSHEET_CREATE_REQUEST = 'SPREADSHEET_CREATE_REQUEST';
export const SPREADSHEET_CREATE_SUCCESS = 'SPREADSHEET_CREATE_SUCCESS';
export const SPREADSHEET_CREATE_FAIL = 'SPREADSHEET_CREATE_FAIL';
