export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const AUTH_TOKENS_UPDATE_REQUEST = "AUTH_TOKENS_UPDATE_REQUEST"
export const AUTH_TOKENS_UPDATE_SUCCESS = "AUTH_TOKENS_UPDATE_SUCCESS"
export const AUTH_TOKENS_UPDATE_FAIL = "AUTH_TOKENS_UPDATE_FAIL"
export const AUTH_TOKENS_CLEAR = 'AUTH_TOKENS_CLEAR';