version: '3.9'

services:
  backend:
    build:
      context: ./grid_scope_backend
    volumes:
      - ./grid_scope_backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mssql
      
  frontend:
    build:
      context: ./grid_scope_frontend
    volumes:
      - ./grid_scope_frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  mssql_init:
    build:
      context: ./mssql_init
    depends_on:
      - mssql
    volumes:
      - ./mssql_init/initdb.sql:/initdb.sql
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
    entrypoint: ["/bin/bash", "/init.sh"]


volumes:
  mssql_data: