version: '3.9'

services:
  backend:
    build:
      context: ./grid_scope_backend
    volumes:
      - ./grid_scope_backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      
  frontend:
    build:
      context: ./grid_scope_frontend
    volumes:
      - ./grid_scope_frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./initdb.sql:/initdb.sql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-N","-C", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10

  mssql-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./initdb.sql:/initdb.sql
    entrypoint: >
      /bin/bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P YourStrong!Passw0rd -N -C -i /initdb.sql
      "

volumes:
  mssql_data: