FROM node:20 AS build

ARG REACT_APP_BACKEND_ADDRESS
ENV REACT_APP_BACKEND_ADDRESS=$REACT_APP_BACKEND_ADDRESS
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]