# Generated by Django 5.0.14 on 2025-08-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheetin',
            name='worksheet_id',
        ),
        migrations.RemoveField(
            model_name='spreadsheetout',
            name='worksheet_id',
        ),
        migrations.AddField(
            model_name='spreadsheetin',
            name='worksheet_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spreadsheetout',
            name='worksheet_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
